WebApplication/Models/Feedback.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication.Models
{
    public class Feedback
    {
        [Display(Name = "ID")]
        public int Id { get; set; }

        [Display(Name = "Пользователь")]
        public int? UserId { get; set; }
        public User User { get; set; }

        [StringLength(20)]
        [Required(ErrorMessage = "Необходимо заполнить название")]
        [Display(Name = "Название")]
        public string Name { get; set; }

        [StringLength(1000)]
        [Display(Name = "Контент")]
        public string Content { get; set; }
    }
}

WebApplication/Areas/Administration/Controllers/FeedbacksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication.Models;
using WebApplication.Models.Contexts;

namespace WebApplication.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class FeedbacksController : Controller
    {
        private readonly WebApplicationContext _context;

        public FeedbacksController(WebApplicationContext context)
        {
            _context = context;
        }

        // GET: Administration/Feedbacks
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Feedbacks.ToListAsync());
        }

        // GET: Administration/Feedbacks/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedback = await _context.Feedbacks
                .Include(u => u.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (feedback == null)
            {
                return NotFound();
            }

            return View(feedback);
        }

        // GET: Administration/Feedbacks/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Login");
            return View();
        }

        // POST: Administration/Feedbacks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create(Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                _context.Add(feedback);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Login", feedback.UserId);
            return View(feedback);
        }

        // GET: Administration/Feedbacks/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedback = await _context.Feedbacks.SingleOrDefaultAsync(m => m.Id == id);
            if (feedback == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Login", feedback.UserId);
            return View(feedback);
        }

        // POST: Administration/Feedbacks/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, Feedback feedback)
        {
            if (id != feedback.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(feedback);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeedbackExists(feedback.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Login", feedback.UserId);
            return View(feedback);
        }

        // GET: Administration/Feedbacks/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var feedback = await _context.Feedbacks
                .Include(u => u.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (feedback == null)
            {
                return NotFound();
            }

            return View(feedback);
        }

        // POST: Administration/Feedbacks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var feedback = await _context.Feedbacks.SingleOrDefaultAsync(m => m.Id == id);
            _context.Feedbacks.Remove(feedback);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FeedbackExists(int id)
        {
            return _context.Feedbacks.Any(e => e.Id == id);
        }
    }
}

WebApplication/Areas/Administration/Views/Feedbacks/Create.cshtml
@model WebApplication.Models.Feedback
@{
    ViewData["Title"] = "Добавление";
}

<nav class="nav-container white">
    <div class="nav-wrapper">
        <div class="col s12">
            <a asp-controller="Feedbacks" asp-action="Index" asp-area="Administration" class="breadcrumb teal-text">Отзывы</a>
            <a class="breadcrumb grey-text breadcrumb-child active">@ViewData["Title"]</a>
        </div>
    </div>
</nav>

<div class="crud-container white z-depth-1 s12">
    <h4 class="teal-text">@ViewData["Title"]</h4>
    <hr class="hr-crud-split" />
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="input-field">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="input-field">
            <label asp-for="Content" class="control-label"></label>
            <textarea asp-for="Content" class="materialize-textarea"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
        <br/>
        <div class="input-field">
            <select asp-for="UserId" asp-items="ViewBag.UserId"></select>
            <label asp-for="UserId"></label>
            <span asp-validation-for="UserId" class="text-danger"></span>
        </div>
        <center>
            <button type="submit" class="btn btn-large waves-effect waves-light teal crud-command-button" asp-controller="Feedbacks" asp-area="Administration" asp-action="Create">Добавить</button>
        </center>
    </form>
</div>
<script>
    $(document).ready(function () {
        $('select').formSelect();
    });
</script>

WebApplication/Areas/Administration/Views/Feedbacks/Delete.cshtml
@model WebApplication.Models.Feedback

@{
    ViewData["Title"] = "Удаление";
}

<nav class="nav-container white">
    <div class="nav-wrapper">
        <div class="col s12">
            <a asp-controller="Feedbacks" asp-action="Index" asp-area="Administration" class="breadcrumb teal-text">Отзывы</a>
            <a class="breadcrumb grey-text breadcrumb-child active">@ViewData["Title"]</a>
        </div>
    </div>
</nav>

<div class="crud-container white z-depth-1 s1">
    <h4 class="teal-text">Вы уверены что хотите это удалить?</h4>
    <hr class="hr-crud-split" />
    <dl class="dl-horizontal">
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="details-dd">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="details-dd">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.User.Login)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.Login)
        </dd>
    </dl>
    <hr class="hr-crud-split" />
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <center>
            <button type="submit" class="btn btn-large waves-effect waves-light teal crud-command-button" asp-controller="Feedbacks" asp-area="Administration" asp-action="Delete">Удалить</button>
        </center>
    </form>
</div>

WebApplication/Areas/Administration/Views/Feedbacks/Details.cshtml
@model WebApplication.Models.Feedback
@{
    ViewData["Title"] = "Информация";
}

<nav class="nav-container white">
    <div class="nav-wrapper">
        <div class="col s12">
            <a asp-controller="Feedbacks" asp-action="Index" asp-area="Administration" class="breadcrumb teal-text">Отзывы</a>
            <a class="breadcrumb grey-text breadcrumb-child active">@ViewData["Title"]</a>
        </div>
    </div>
</nav>

<div class="crud-container white z-depth-1 s1">
    <h4 class="teal-text">@ViewData["Title"]</h4>
    <hr class="hr-crud-split" />
    <dl class="dl-horizontal">
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="details-dd">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="details-dd">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.User.Login)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.Login)
        </dd>
    </dl>
</div>

WebApplication/Areas/Administration/Views/Feedbacks/Edit.cshtml
@model WebApplication.Models.Feedback
@{
    ViewData["Title"] = "Редактирование";
}

<nav class="nav-container white">
    <div class="nav-wrapper">
        <div class="col s12">
            <a asp-controller="Feedbacks" asp-action="Index" asp-area="Administration" class="breadcrumb teal-text">Отзывы</a>
            <a class="breadcrumb grey-text breadcrumb-child active">@ViewData["Title"]</a>
        </div>
    </div>
</nav>

<div class="crud-container white z-depth-1 s1">
    <h4 class="teal-text">@ViewData["Title"]</h4>
    <hr class="hr-crud-split" />
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="control-label"></label>
            <textarea asp-for="Content" class="materialize-textarea"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
        <br />
        <div class="input-field">
            <select asp-for="UserId" asp-items="ViewBag.UserId"></select>
            <label asp-for="UserId"></label>
            <span asp-validation-for="UserId" class="text-danger"></span>
        </div>
        <center>
            <button type="submit" class="btn btn-large waves-effect waves-light teal crud-command-button" asp-controller="Feedbacks" asp-area="Administration" asp-action="Edit">Редактировать</button>
        </center>
    </form>
</div>
<script>
    $(document).ready(function () {
        $('select').formSelect();
    });
</script>

WebApplication/Areas/Administration/Views/Feedbacks/Index.cshtml
@model IEnumerable<WebApplication.Models.Feedback>

@{
    ViewData["Title"] = "Отзывы";
}

<div class="crud-container white z-depth-1 s1">
    <h4 class="teal-text">@ViewData["Title"]</h4>
    <table class="striped ">
        <thead>
            <tr class="crud-header">
                <th>ID</th>
                <th>Название</th>
                <th class="crud-command-actions">Действия</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var role in Model)
            {
                <tr>
                    <td>@role.Id</td>
                    <td>@role.Name</td>
                    <td class="crud-command-actions">
                        <a asp-controller="Feedbacks" asp-area="Administration" asp-action="Details" asp-route-id="@role.Id"><i class="material-icons small teal-text">remove_red_eye</i></a>
                        <a asp-controller="Feedbacks" asp-area="Administration" asp-action="Edit" asp-route-id="@role.Id"><i class="material-icons small teal-text">edit</i></a>
                        <a asp-controller="Feedbacks" asp-area="Administration" asp-action="Delete" asp-route-id="@role.Id"><i class="material-icons small teal-text">delete</i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <hr class="hr-crud-split" />
    <center>
        <a class="btn btn-large waves-effect waves-light teal crud-command-button" asp-controller="Feedbacks" asp-area="Administration" asp-action="Create">Добавить</a>
    </center>
</div>