WebApplication/Models/Vote.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WebApplication.Models
{
    public class Vote
    {
        [Display(Name = "ID")]
        public int Id { get; set; }

        [Display(Name = "Пользователь")]
        public int? UserId { get; set; }
        public User User { get; set; }

        [Display(Name = "Отзыв")]
        public int? FeedbackId { get; set; }
        public Feedback Feedback { get; set; }

        [Required(ErrorMessage = "Необходимо указать оценку")]
        [Display(Name = "Оценка")]
        public int RatingGiven { get; set; }

        [Required(ErrorMessage = "Необходимо указать время")]
        [Display(Name = "Время")]
        public DateTime Time { get; set; }

        [Display(Name = "Голос возвращен")]
        public bool VoteReturned { get; set; }
    }
}

WebApplication/Areas/Administration/Controllers/VotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication.Models;
using WebApplication.Models.Contexts;

namespace WebApplication.Areas.Administration.Controllers
{
    [Area("Administration")]
    public class VotesController : Controller
    {
        private readonly WebApplicationContext _context;

        public VotesController(WebApplicationContext context)
        {
            _context = context;
        }

        // GET: Administration/Votes
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {
            var webApplicationContext = _context.Votes.Include(v => v.Feedback).Include(v => v.User);
            return View(await webApplicationContext.ToListAsync());
        }

        // GET: Administration/Votes/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vote = await _context.Votes
                .Include(v => v.Feedback)
                .Include(v => v.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (vote == null)
            {
                return NotFound();
            }

            return View(vote);
        }

        // GET: Administration/Votes/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewData["FeedbackId"] = new SelectList(_context.Feedbacks, "Id", "Name");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Login");
            return View();
        }

        // POST: Administration/Votes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create(Vote vote)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vote);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FeedbackId"] = new SelectList(_context.Feedbacks, "Id", "Name", vote.FeedbackId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Login", vote.UserId);
            return View(vote);
        }

        // GET: Administration/Votes/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vote = await _context.Votes.SingleOrDefaultAsync(m => m.Id == id);
            if (vote == null)
            {
                return NotFound();
            }
            ViewData["FeedbackId"] = new SelectList(_context.Feedbacks, "Id", "Name", vote.FeedbackId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Login", vote.UserId);
            return View(vote);
        }

        // POST: Administration/Votes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int id, Vote vote)
        {
            if (id != vote.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vote);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VoteExists(vote.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FeedbackId"] = new SelectList(_context.Feedbacks, "Id", "Name", vote.FeedbackId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Login", vote.UserId);
            return View(vote);
        }

        // GET: Administration/Votes/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vote = await _context.Votes
                .Include(v => v.Feedback)
                .Include(v => v.User)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (vote == null)
            {
                return NotFound();
            }

            return View(vote);
        }

        // POST: Administration/Votes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vote = await _context.Votes.SingleOrDefaultAsync(m => m.Id == id);
            _context.Votes.Remove(vote);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VoteExists(int id)
        {
            return _context.Votes.Any(e => e.Id == id);
        }
    }
}

WebApplication/Areas/Administration/Views/Votes/Create.cshtml
@model WebApplication.Models.Vote

@{
    ViewData["Title"] = "Добавление";
}

<nav class="nav-container white">
    <div class="nav-wrapper">
        <div class="col s12">
            <a asp-controller="Votes" asp-action="Index" asp-area="Administration" class="breadcrumb teal-text">Голоса</a>
            <a class="breadcrumb grey-text breadcrumb-child active">@ViewData["Title"]</a>
        </div>
    </div>
</nav>

<div class="crud-container white z-depth-1 s1">
    <h4 class="teal-text">@ViewData["Title"]</h4>
    <hr class="hr-crud-split" />
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <br />
        <div class="input-field">
            <select asp-for="UserId" asp-items="ViewBag.UserId"></select>
            <label asp-for="UserId"></label>
            <span asp-validation-for="UserId" class="text-danger"></span>
        </div>
        <br />
        <div class="input-field">
            <select asp-for="FeedbackId" asp-items="ViewBag.FeedbackId"></select>
            <label asp-for="FeedbackId"></label>
            <span asp-validation-for="FeedbackId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="RatingGiven" class="control-label"></label>
            <input asp-for="RatingGiven" class="form-control" />
            <span asp-validation-for="RatingGiven" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Time" class="control-label"></label>
            <input asp-for="Time" class="form-control" />
            <span asp-validation-for="Time" class="text-danger"></span>
        </div>
        <div class="input-field">
            <label>
                <input type="checkbox" asp-for="VoteReturned" />
                <span>Голос возвращен</span>
            </label>
            <span asp-validation-for="VoteReturned" class="text-danger"></span>
        </div>
        <br />
        <br />
        <hr class="hr-crud-split" />
        <center>
            <button type="submit" class="btn btn-large waves-effect waves-light teal crud-command-button" asp-controller="Votes" asp-area="Administration" asp-action="Create">Добавить</button>
        </center>
    </form>
</div>

<script>
    $(document).ready(function () {
        $('select').formSelect();
    });
</script>

WebApplication/Areas/Administration/Views/Votes/Delete.cshtml
@model WebApplication.Models.Vote
@{
    ViewData["Title"] = "Удаление";
}

<nav class="nav-container white">
    <div class="nav-wrapper">
        <div class="col s12">
            <a asp-controller="Votes" asp-action="Index" asp-area="Administration" class="breadcrumb teal-text">Голоса</a>
            <a class="breadcrumb grey-text breadcrumb-child active">@ViewData["Title"]</a>
        </div>
    </div>
</nav>

<div class="crud-container white z-depth-1 s1">
    <h4 class="teal-text">Вы уверены что хотите это удалить?</h4>
    <hr class="hr-crud-split" />
    <dl class="dl-horizontal">
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.User.Login)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.Login)
        </dd>
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.Feedback.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Feedback.Name)
        </dd>
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.RatingGiven)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RatingGiven)
        </dd>
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.VoteReturned)
        </dt>
        <dd>
            @Model.VoteReturned.ToString()
        </dd>
    </dl>
    <hr class="hr-crud-split" />
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <center>
            <button type="submit" class="btn btn-large waves-effect waves-light teal crud-command-button" asp-controller="Votes" asp-area="Administration" asp-action="Delete">Удалить</button>
        </center>
    </form>
</div>

WebApplication/Areas/Administration/Views/Votes/Details.cshtml
@model WebApplication.Models.Vote
@{
    ViewData["Title"] = "Информация";
}

<nav class="nav-container white">
    <div class="nav-wrapper">
        <div class="col s12">
            <a asp-controller="Votes" asp-action="Index" asp-area="Administration" class="breadcrumb teal-text">Голоса</a>
            <a class="breadcrumb grey-text breadcrumb-child active">@ViewData["Title"]</a>
        </div>
    </div>
</nav>

<div class="crud-container white z-depth-1 s1">
    <h4 class="teal-text">@ViewData["Title"]</h4>
    <hr class="hr-crud-split" />
    <dl class="dl-horizontal">
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.User.Login)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.Login)
        </dd>
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.Feedback.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Feedback.Name)
        </dd>
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.RatingGiven)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RatingGiven)
        </dd>
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.Time)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Time)
        </dd>
        <dt class="details-dt">
            @Html.DisplayNameFor(model => model.VoteReturned)
        </dt>
        <dd>
            @Model.VoteReturned.ToString()
        </dd>
    </dl>
</div>

WebApplication/Areas/Administration/Views/Votes/Edit.cshtml
@model WebApplication.Models.Vote
@{
    ViewData["Title"] = "Редактирование";
}

<nav class="nav-container white">
    <div class="nav-wrapper">
        <div class="col s12">
            <a asp-controller="Votes" asp-action="Index" asp-area="Administration" class="breadcrumb teal-text">Голоса</a>
            <a class="breadcrumb grey-text breadcrumb-child active">@ViewData["Title"]</a>
        </div>
    </div>
</nav>

<div class="crud-container white z-depth-1 s1">
    <h4 class="teal-text">@ViewData["Title"]</h4>
    <hr class="hr-crud-split" />
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <br />
        <div class="input-field">
            <select asp-for="UserId" asp-items="ViewBag.UserId"></select>
            <label asp-for="UserId"></label>
            <span asp-validation-for="UserId" class="text-danger"></span>
        </div>
        <br />
        <div class="input-field">
            <select asp-for="FeedbackId" asp-items="ViewBag.FeedbackId"></select>
            <label asp-for="FeedbackId"></label>
            <span asp-validation-for="FeedbackId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="RatingGiven" class="control-label"></label>
            <input asp-for="RatingGiven" class="form-control" />
            <span asp-validation-for="RatingGiven" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Time" class="control-label"></label>
            <input asp-for="Time" class="form-control" />
            <span asp-validation-for="Time" class="text-danger"></span>
        </div>
        <div class="input-field">
            <label>
                <input type="checkbox" asp-for="VoteReturned" />
                <span>Голос возвращен</span>
            </label>
            <span asp-validation-for="VoteReturned" class="text-danger"></span>
        </div>
        <br />
        <br />
        <hr class="hr-crud-split" />
        <center>
            <button type="submit" class="btn btn-large waves-effect waves-light teal crud-command-button" asp-controller="Votes" asp-area="Administration" asp-action="Edit">Редактировать</button>
        </center>
    </form>
</div>

<script>
    $(document).ready(function () {
        $('select').formSelect();
    });
</script>

WebApplication/Areas/Administration/Views/Votes/Index.cshtml
@model IEnumerable<WebApplication.Models.Vote>

@{
    ViewData["Title"] = "Голоса";
}

<div class="crud-container white z-depth-1 s1">
    <h4 class="teal-text">@ViewData["Title"]</h4>
    <table class="striped ">
        <thead>
            <tr class="crud-header">
                <th>ID</th>
                <th>Пользователь</th>
                <th>Отзыв</th>
                <th>Оценка</th>
                <th class="crud-command-actions">Действия</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var vote in Model)
            {
            <tr>
                <td>@vote.Id</td>
                <td>@vote.User.Login</td>
                <td>@vote.Feedback.Name</td>
                <td>@vote.RatingGiven</td>
                <td class="crud-command-actions">
                    <a asp-controller="Votes" asp-area="Administration" asp-action="Details" asp-route-id="@vote.Id"><i class="material-icons small teal-text">remove_red_eye</i></a>
                    <a asp-controller="Votes" asp-area="Administration" asp-action="Edit" asp-route-id="@vote.Id"><i class="material-icons small teal-text">edit</i></a>
                    <a asp-controller="Votes" asp-area="Administration" asp-action="Delete" asp-route-id="@vote.Id"><i class="material-icons small teal-text">delete</i></a>
                </td>
            </tr>
            }
        </tbody>
    </table>
    <hr class="hr-crud-split" />
    <center>
        <a class="btn btn-large waves-effect waves-light teal crud-command-button" asp-controller="Votes" asp-area="Administration" asp-action="Create">Добавить</a>
    </center>
</div>